In [ ]:
import numpy as np

a = np.array([2,3,4])

print(a,type(a))

array1 = np.array([6,3,5,8,10])
array2 = np.array([1,5,2,4,15])

# adition

adition_resualt = array1 + array2
print(adition_resualt,type(adition_resualt))

# substaction

sub_resualt = array1 - array2
print(sub_resualt,type(sub_resualt))

# multipication

multipication_resualt = array1 * array2
print(multipication_resualt,type(multipication_resualt))

# divition

divition_resualt = array1 / array2
print(divition_resualt,type(divition_resualt))

result = np.max(array1)
result2 = np.min(array1)
print(result,type)
print(result2,type)


[2 3 4] <class 'numpy.ndarray'>
[ 7  8  7 12 25] <class 'numpy.ndarray'>
[ 5 -2  3  4 -5] <class 'numpy.ndarray'>
[  6  15  10  32 150] <class 'numpy.ndarray'>
[6.         0.6        2.5        2.         0.66666667] <class 'numpy.ndarray'>
10 <class 'type'>
3 <class 'type'>


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [20]:
import numpy as np

array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])#2D array
print(array_1.shape)

array_2 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(array_2.shape)

(2, 5)
(2, 2, 5)
