In [191]:
import numpy as np

a = np.array([2,3,4])

print(a,type(a))

array1 = np.array([6,3,5,8,10])
array2 = np.array([1,5,2,4,15])

# adition

adition_resualt = array1 + array2
print(adition_resualt,type(adition_resualt))

# substaction

sub_resualt = array1 - array2
print(sub_resualt,type(sub_resualt))

# multipication

multipication_resualt = array1 * array2
print(multipication_resualt,type(multipication_resualt))

# divition

divition_resualt = array1 / array2
print(divition_resualt,type(divition_resualt))

result = np.max(array1)
result2 = np.min(array1)
print(result,type)
print(result2,type)


[2 3 4] <class 'numpy.ndarray'>
[ 7  8  7 12 25] <class 'numpy.ndarray'>
[ 5 -2  3  4 -5] <class 'numpy.ndarray'>
[  6  15  10  32 150] <class 'numpy.ndarray'>
[6.         0.6        2.5        2.         0.66666667] <class 'numpy.ndarray'>
10 <class 'type'>
3 <class 'type'>


In [192]:
import numpy as np

array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])#2D array same values must be same in length
print(array_1.shape)

array_2 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])#3D array
print(array_2[1,0,3])#selecting the array value

print(array_2.shape)

array= np.array([1,2,3])
print(array.dtype)
print(array.size)

(2, 5)
14
(2, 2, 5)
int64
3


In [193]:
array = np.array([[[1,2], [3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(array.ndim)

3


In [194]:
import math 

array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

array_3 = array_1 + 10
print(array_3,"\n")
array_3 *=2
print(array_3,"\n")
array_4= array_3 **2
print(array_4)    

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]] 

[[ 484  576  676  784  900]
 [1024 1156 1296 1444 1600]
 [1764 1936 2116 2304 2500]
 [2704 2916 3136 3364 3600]]


In [195]:
import numpy as np
array_5 = np.array([10,11,12,13,13])
con = array_5 >12
fil = array_5[con]
print(fil)

[13 13]


In [196]:
array = np.array([10,20,30,40,50])
fil = array[(array>20)&(array<50)]
print(fil)

[30 40]


In [197]:
array = np.zeros(5)

print(array)

array_2 = np.zeros((2,3))

print("\n",array_2)

[0. 0. 0. 0. 0.]

 [[0. 0. 0.]
 [0. 0. 0.]]


In [198]:
array = np.full(4,7)
print("\n",array)

array_2 = np.full((2,3),8)

print("\n",array_2)


 [7 7 7 7]

 [[8 8 8]
 [8 8 8]]


In [199]:
array = np.empty((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [200]:
# *Create one dimensional numpy array with values 1 to 20 use Boolean index into extract all even numbers

# *Create a numpy array with elements 10,20,30,40,50 use Boolean index in to extract own elements greater than the mean of the array


array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
con = array%2 == 0
fil = array[con]
print(fil,"/n")

# array_2 = np.array([10,20,30,40,50])
# con = array_2 + array_2 / len(array)> array_2
# print("\n",con)

array_2 = np.array([10,20,30,40,50])
mean_value = np.mean(array_2)
fil = array_2[array_2>mean_value]
print("\n",fil)


[ 2  4  6  8 10 12 14 16 18 20] /n

 [40 50]


In [201]:
import pandas as pd

data = {'Name': ['John', 'Anna', 'Peter', 'Linda'],
        'Age': [25, 33, 27, 29],
        'City': ['New York', 'Los Angeles', 'Paris', 'Tokyo']}
df = pd.DataFrame(data)
print(df)

print("\n",df.loc[0,"Name"])
print("\n",df.loc[0,"Age"])
print("\n",df.loc[1])
print("\n",df.loc[[0,1]]) #returns multiple rows


    Name  Age         City
0   John   25     New York
1   Anna   33  Los Angeles
2  Peter   27        Paris
3  Linda   29        Tokyo

 John

 25

 Name           Anna
Age              33
City    Los Angeles
Name: 1, dtype: object

    Name  Age         City
0  John   25     New York
1  Anna   33  Los Angeles


In [246]:
import pandas as pd
data={
  "calories":[420,220,500],
  "duration":[50,45,60]
}

df = pd.DataFrame(data,index = ["day 1","day 2","day 3"])
print(df)
print("\n",df.loc["day 2"])
print("\n",df.loc[["day 1","day 3"]])
print("\n",df["calories"])
print("\n",df.shape)

       calories  duration
day 1       420        50
day 2       220        45
day 3       500        60

 calories    220
duration     45
Name: day 2, dtype: int64

        calories  duration
day 1       420        50
day 3       500        60

 day 1    420
day 2    220
day 3    500
Name: calories, dtype: int64

 (3, 2)


In [203]:
df = pd.DataFrame({'A':[1,2],'B':[3,4]})
print(df.columns)
print(list(df.columns))
print(df.size)

Index(['A', 'B'], dtype='object')
['A', 'B']
4


In [204]:
import pandas as pd
df = pd.DataFrame({'A':[1,2],'B':[3,4]})
print(df.values)
print(type(df))

[[1 3]
 [2 4]]
<class 'pandas.core.frame.DataFrame'>


In [205]:
import pandas as pd
data={
  "calories":[420,220,500],
  "duration":[50,45,60]
}

df = pd.DataFrame(data)
print(len(df))


3


In [251]:
import pandas as pd

data={
    "order ID":[101,102,103,104,105],
    "product":["laptop","smartphone","deskchair","Mointor","bookshelf"],
    "category":["electronic","electronic","furniture","electronic","furniture"],
    "Quantity":[2,5,10,4,2],
    "price of unit":[1000,800,150,200,300],
    "region":["north","south","east","west","north"]
}

df = pd.DataFrame(data)
df['total'] = df["Quantity"]*df["price of unit"]
list[df]
print(df)

fil = max(df["total"])
# print('product name highest price')
print("\n","most sale product value:",fil) 

   order ID     product    category  Quantity  price of unit region  total
0       101      laptop  electronic         2           1000  north   2000
1       102  smartphone  electronic         5            800  south   4000
2       103   deskchair   furniture        10            150   east   1500
3       104     Mointor  electronic         4            200   west    800
4       105   bookshelf   furniture         2            300  north    600

 most sale product value: 4000


In [256]:
data = {
    'Age':[25,30,35,40],
    'Salary':[50000,60000,70000,80000]
}

df = pd.DataFrame(data)
print(df.mean())
print("\n",df.describe())
filtered = df[df["Age"]>25]

print("\n",filtered,type(filtered))


Age          32.5
Salary    65000.0
dtype: float64

              Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000

    Age  Salary
1   30   60000
2   35   70000
3   40   80000 <class 'pandas.core.frame.DataFrame'>


In [ ]:
df = pd.DataFrame({'A':[1,2],'B':[3,4]})
df.loc[len(df)] = [5,6]

print(df)


   A  B
0  1  3
1  2  4
2  5  6


In [267]:
df = pd.DataFrame({'A':[1,2],'B':[3,4]})
df.loc[len(df)] = [5,6]
print(df,)
dfdrop = df.drop('A',axis=1)
print(dfdrop)

dfdrop = df.drop(0,axis=0)
print("\n",dfdrop)


   A  B
0  1  3
1  2  4
2  5  6
   B
0  3
1  4
2  6

    A  B
1  2  4
2  5  6


In [274]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df,"\n",type(df))

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...    

In [ ]:

import pandas as pd
df = pd.read_csv('read.json')# read.json must be wrapped by pandas
print(df)

ValueError: If using all scalar values, you must pass an index