In [21]:
import numpy as np

a = np.array([2,3,4])

print(a,type(a))

array1 = np.array([6,3,5,8,10])
array2 = np.array([1,5,2,4,15])

# adition

adition_resualt = array1 + array2
print(adition_resualt,type(adition_resualt))

# substaction

sub_resualt = array1 - array2
print(sub_resualt,type(sub_resualt))

# multipication

multipication_resualt = array1 * array2
print(multipication_resualt,type(multipication_resualt))

# divition

divition_resualt = array1 / array2
print(divition_resualt,type(divition_resualt))

result = np.max(array1)
result2 = np.min(array1)
print(result,type)
print(result2,type)


[2 3 4] <class 'numpy.ndarray'>
[ 7  8  7 12 25] <class 'numpy.ndarray'>
[ 5 -2  3  4 -5] <class 'numpy.ndarray'>
[  6  15  10  32 150] <class 'numpy.ndarray'>
[6.         0.6        2.5        2.         0.66666667] <class 'numpy.ndarray'>
10 <class 'type'>
3 <class 'type'>


In [ ]:
import numpy as np

array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])#2D array same values must be same in length
print(array_1.shape)

array_2 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])#3D array
print(array_2[1,0,3])#selecting the array value

print(array_2.shape)

array= np.array([1,2,3])
print(array.dtype)
print(array.size)

(2, 5)
14
(2, 2, 5)
int64
3


In [32]:
array = np.array([[[1,2], [3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(array.ndim)

3


In [68]:
import math 

array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

array_3 = array_1 + 10
print(array_3,"\n")
array_3 *=2
print(array_3,"\n")
array_4= array_3 **2
print(array_4)    

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]] 

[[ 484  576  676  784  900]
 [1024 1156 1296 1444 1600]
 [1764 1936 2116 2304 2500]
 [2704 2916 3136 3364 3600]]


In [67]:
import numpy as np
array_5 = np.array([10,11,12,13,13])
con = array_5 >12
fil = array_5[con]
print(fil)

[13 13]


In [70]:
array = np.array([10,20,30,40,50])
fil = array[(array>20)&(array<50)]
print(fil)

[30 40]


In [72]:
array = np.zeros(5)

print(array)

array_2 = np.zeros((2,3))

print("\n",array_2)

[0. 0. 0. 0. 0.]

 [[0. 0. 0.]
 [0. 0. 0.]]


In [74]:
array = np.full(4,7)
print("\n",array)

array_2 = np.full((2,3),8)

print("\n",array_2)


 [7 7 7 7]

 [[8 8 8]
 [8 8 8]]


In [102]:
array = np.empty((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [118]:
# *Create one dimensional numpy array with values 1 to 20 use Boolean index into extract all even numbers

# *Create a numpy array with elements 10,20,30,40,50 use Boolean index in to extract own elements greater than the mean of the array


array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
con = array%2 == 0
fil = array[con]
print(fil,"/n")

# array_2 = np.array([10,20,30,40,50])
# con = array_2 + array_2 / len(array)> array_2
# print("\n",con)

array_2 = np.array([10,20,30,40,50])
mean_value = np.mean(array_2)
fil = array_2[array_2>mean_value]
print("\n",fil)


[ 2  4  6  8 10 12 14 16 18 20] /n

 [40 50]


In [ ]:
import pandas as pd

data = {'Name': ['John', 'Anna', 'Peter', 'Linda'],
        'Age': [25, 33, 27, 29],
        'City': ['New York', 'Los Angeles', 'Paris', 'Tokyo']}
df = pd.DataFrame(data)
print(df)

print("\n",df.loc[0,"Name"])
print("\n",df.loc[0,"Age"])
print("\n",df.loc[1])
print("\n",df.loc[[0,1]]) #returns multiple rows


    Name  Age         City
0   John   25     New York
1   Anna   33  Los Angeles
2  Peter   27        Paris
3  Linda   29        Tokyo

 John

 25

 Name           Anna
Age              33
City    Los Angeles
Name: 1, dtype: object

    Name  Age         City
0  John   25     New York
1  Anna   33  Los Angeles


In [144]:
import pandas as pd
data={
  "calories":[420,220,500],
  "duration":[50,45,60]
}

df = pd.DataFrame(data,index = ["day 1","day 2","day 3"])
print(df)
print("\n",df.loc["day 2"])
print("\n",df.loc[["day 1","day 3"]])
print("\n",df["calories"])
print("\n",df.shape)

       calories  duration
day 1       420        50
day 2       220        45
day 3       500        60

 calories    220
duration     45
Name: day 2, dtype: int64

        calories  duration
day 1       420        50
day 3       500        60

 day 1    420
day 2    220
day 3    500
Name: calories, dtype: int64

 (3, 2)
