In [2]:
import numpy as np

a = np.array([2,3,4])

print(a,type(a))

array1 = np.array([6,3,5,8,10])
array2 = np.array([1,5,2,4,15])

# adition

adition_resualt = array1 + array2
print(adition_resualt,type(adition_resualt))

# substaction

sub_resualt = array1 - array2
print(sub_resualt,type(sub_resualt))

# multipication

multipication_resualt = array1 * array2
print(multipication_resualt,type(multipication_resualt))

# divition

divition_resualt = array1 / array2
print(divition_resualt,type(divition_resualt))

result = np.max(array1)
result2 = np.min(array1)
print(result,type)
print(result2,type)


[2 3 4] <class 'numpy.ndarray'>
[ 7  8  7 12 25] <class 'numpy.ndarray'>
[ 5 -2  3  4 -5] <class 'numpy.ndarray'>
[  6  15  10  32 150] <class 'numpy.ndarray'>
[6.         0.6        2.5        2.         0.66666667] <class 'numpy.ndarray'>
10 <class 'type'>
3 <class 'type'>


In [3]:
import numpy as np

array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])#2D array same values must be same in length
print(array_1.shape)

array_2 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])#3D array
print(array_2[1,0,3])#selecting the array value

print(array_2.shape)

array= np.array([1,2,3])
print(array.dtype)
print(array.size)

(2, 5)
14
(2, 2, 5)
int64
3


In [4]:
array = np.array([[[1,2], [3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(array.ndim)

3


In [5]:
import math 

array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

array_3 = array_1 + 10
print(array_3,"\n")
array_3 *=2
print(array_3,"\n")
array_4= array_3 **2
print(array_4)    

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]] 

[[ 484  576  676  784  900]
 [1024 1156 1296 1444 1600]
 [1764 1936 2116 2304 2500]
 [2704 2916 3136 3364 3600]]


In [6]:
import numpy as np
array_5 = np.array([10,11,12,13,13])
con = array_5 >12
fil = array_5[con]
print(fil)

[13 13]


In [7]:
array = np.array([10,20,30,40,50])
fil = array[(array>20)&(array<50)]
print(fil)

[30 40]


In [8]:
array = np.zeros(5)

print(array)

array_2 = np.zeros((2,3))

print("\n",array_2)

[0. 0. 0. 0. 0.]

 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
array = np.full(4,7)
print("\n",array)

array_2 = np.full((2,3),8)

print("\n",array_2)


 [7 7 7 7]

 [[8 8 8]
 [8 8 8]]


In [10]:
array = np.empty((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# *Create one dimensional numpy array with values 1 to 20 use Boolean index into extract all even numbers

# *Create a numpy array with elements 10,20,30,40,50 use Boolean index in to extract own elements greater than the mean of the array


array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
con = array%2 == 0
fil = array[con]
print(fil,"/n")

# array_2 = np.array([10,20,30,40,50])
# con = array_2 + array_2 / len(array)> array_2
# print("\n",con)

array_2 = np.array([10,20,30,40,50])
mean_value = np.mean(array_2)
fil = array_2[array_2>mean_value]
print("\n",fil)


[ 2  4  6  8 10 12 14 16 18 20] /n

 [40 50]


In [12]:
import pandas as pd

data = {'Name': ['John', 'Anna', 'Peter', 'Linda'],
        'Age': [25, 33, 27, 29],
        'City': ['New York', 'Los Angeles', 'Paris', 'Tokyo']}
df = pd.DataFrame(data)
print(df)

print("\n",df.loc[0,"Name"])
print("\n",df.loc[0,"Age"])
print("\n",df.loc[1])
print("\n",df.loc[[0,1]]) #returns multiple rows


    Name  Age         City
0   John   25     New York
1   Anna   33  Los Angeles
2  Peter   27        Paris
3  Linda   29        Tokyo

 John

 25

 Name           Anna
Age              33
City    Los Angeles
Name: 1, dtype: object

    Name  Age         City
0  John   25     New York
1  Anna   33  Los Angeles


In [13]:
import pandas as pd
data={
  "calories":[420,220,500],
  "duration":[50,45,60]
}

df = pd.DataFrame(data,index = ["day 1","day 2","day 3"])
print(df)
print("\n",df.loc["day 2"])
print("\n",df.loc[["day 1","day 3"]])
print("\n",df["calories"])
print("\n",df.shape)

       calories  duration
day 1       420        50
day 2       220        45
day 3       500        60

 calories    220
duration     45
Name: day 2, dtype: int64

        calories  duration
day 1       420        50
day 3       500        60

 day 1    420
day 2    220
day 3    500
Name: calories, dtype: int64

 (3, 2)


In [14]:
df = pd.DataFrame({'A':[1,2],'B':[3,4]})
print(df.columns)
print(list(df.columns))
print(df.size)

Index(['A', 'B'], dtype='object')
['A', 'B']
4


In [15]:
import pandas as pd
df = pd.DataFrame({'A':[1,2],'B':[3,4]})
print(df.values)
print(type(df))

[[1 3]
 [2 4]]
<class 'pandas.core.frame.DataFrame'>


In [16]:
import pandas as pd
data={
  "calories":[420,220,500],
  "duration":[50,45,60]
}

df = pd.DataFrame(data)
print(len(df))


3


In [17]:
import pandas as pd

data={
    "order ID":[101,102,103,104,105],
    "product":["laptop","smartphone","deskchair","Mointor","bookshelf"],
    "category":["electronic","electronic","furniture","electronic","furniture"],
    "Quantity":[2,5,10,4,2],
    "price of unit":[1000,800,150,200,300],
    "region":["north","south","east","west","north"]
}

df = pd.DataFrame(data)
df['total'] = df["Quantity"]*df["price of unit"]
list[df]
print(df)

fil = max(df["total"])
# print('product name highest price')
print("\n","most sale product value:",fil) 

   order ID     product    category  Quantity  price of unit region  total
0       101      laptop  electronic         2           1000  north   2000
1       102  smartphone  electronic         5            800  south   4000
2       103   deskchair   furniture        10            150   east   1500
3       104     Mointor  electronic         4            200   west    800
4       105   bookshelf   furniture         2            300  north    600

 most sale product value: 4000


In [18]:
data = {
    'Age':[25,30,35,40],
    'Salary':[50000,60000,70000,80000]
}

df = pd.DataFrame(data)
print(df.mean())
print("\n",df.describe())
filtered = df[df["Age"]>25]

print("\n",filtered,type(filtered))


Age          32.5
Salary    65000.0
dtype: float64

              Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000

    Age  Salary
1   30   60000
2   35   70000
3   40   80000 <class 'pandas.core.frame.DataFrame'>


In [19]:
df = pd.DataFrame({'A':[1,2],'B':[3,4]})
df.loc[len(df)] = [5,6]

print(df)


   A  B
0  1  3
1  2  4
2  5  6


In [20]:
df = pd.DataFrame({'A':[1,2],'B':[3,4]})
df.loc[len(df)] = [5,6]
print(df,)
dfdrop = df.drop('A',axis=1)
print(dfdrop)

dfdrop = df.drop(0,axis=0)
print("\n",dfdrop)


   A  B
0  1  3
1  2  4
2  5  6
   B
0  3
1  4
2  6

    A  B
1  2  4
2  5  6


In [21]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df,"\n",type(df))

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...    

In [22]:

import pandas as pd
df = pd.read_csv('read.json')# read.json must be wrapped by pandas
print(df)

                       {
    "name": "Shalom" NaN
    "age": 21        NaN
    "build": 21      NaN
}                    NaN


In [23]:
import numpy as np
# Create a 1D NumPy array with values from 1 to 50. Use Boolean indexing to extract:


# All odd numbers greater than 25.

array =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])
print(array)
# All numbers divisible by 5.
con = array[array%5==0]
print("\n",con)

con = array[(array%2==0) & (array>25)]
print("\n",con)


    

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

 [ 5 10 15 20 25 30 35 40 45 50]

 [26 28 30 32 34 36 38 40 42 44 46 48 50]


In [24]:
import random
import numpy as np
# Generate a 2D NumPy array of shape (3, 4) filled with random integers between 1 and 100. Find:

# The maximum value in each row.
# The minimum value in each column.

array = np.array([[random.randint(1,100),random.randint(1,100),random.randint(1,100),random.randint(1,100)],[random.randint(1,100),random.randint(1,100),random.randint(1,100),random.randint(1,100)],[random.randint(1,100),random.randint(1,100),random.randint(1,100),random.randint(1,100)]])

print(array)

# The maximum value in each row.
value = np.max(array)
print("\n",value)

# The minimum value in each column.
print("\n")
for x in range(0,len(array[0])):
    value = np.min(array[x])
    print(value,end=" ")


[[15 62 76 10]
 [60 29 78 18]
 [25 34 74 81]]

 81


10 18 25 

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
import numpy as np
# Matrix Operations:

# Create a 3x3 NumPy array with values from 1 to 9.
# Multiply every element by 5 and print the result.
# Compute the transpose of the array.
array = np.array([[[i for i in range(1,10)]], [[i for i in range(1,10)]], [[i for i in range(1,10)]], [[i for i in range(1,10)]]])
print(array)
array1 = array * 5
print("\n",array1)

# Create a 3x3 NumPy array with values from 1 to 9
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Multiply every element by 5
array1 = array * 5

# Compute the transpose of the array
array_transpose = array.T

# Print results
print("Original Array:\n", array)
print("\nArray after multiplying by 5:\n", array1)
print("\nTranspose of the Array:\n", array_transpose)


[[[1 2 3 4 5 6 7 8 9]]

 [[1 2 3 4 5 6 7 8 9]]

 [[1 2 3 4 5 6 7 8 9]]

 [[1 2 3 4 5 6 7 8 9]]]

 [[[ 5 10 15 20 25 30 35 40 45]]

 [[ 5 10 15 20 25 30 35 40 45]]

 [[ 5 10 15 20 25 30 35 40 45]]

 [[ 5 10 15 20 25 30 35 40 45]]]
Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after multiplying by 5:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

Transpose of the Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import pandas as pd
# pandas exercise

# DataFrame Creation:
# Create a DataFrame with the following data:

# python
# Copy code

# Add a new column Grade where scores above 85 are "A" and below are "B".
# Filter and display the rows where Grade is "A".

data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
}
df = pd.DataFrame(data)
df["Grade"] = np.where(df["Score"]> 85 ,"A","B")
grade_dr = df[df["Grade"]== "A"]

print(df)
print("\n",grade_dr)

      Name  Age  Score Grade
0    Alice   24     85     B
1      Bob   27     90     A
2  Charlie   22     78     B
3    David   32     88     A

     Name  Age  Score Grade
1    Bob   27     90     A
3  David   32     88     A


In [ ]:
import numpy as np
# Boolean Indexing:

# Create a NumPy array with values from 1 to 20.
# Extract all numbers divisible by 3

array =np.array([i for i in range(1,21)])
print(array)
con = array%3==0
print(array[con])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]


In [1]:
import numpy as np
import random as ran
import math as mp
# Statistical Functions:

# Create a NumPy array with 10 random integers between 1 and 100.
# Find the maximum, minimum, mean, and standard deviation of the array.
array = np.random.randint(1,100,size=10)
print(array)
print("\n",np.max(array))
print("\n",np.min(array))

print("\n",np.mean(array))
print("\n",np.std(array))


[45 77 32 49 53 85 79 13 47  6]

 85

 6

 48.6

 25.393700006103877


In [21]:
import pandas as pd
import numpy as np
# Create a DataFrame with the following data:

# python
# Copy code
# data = {
#     "Product": ["Laptop", "Phone", "Tablet", "Monitor"],
#     "Price": [1000, 800, 400, 300],
#     "Quantity": [5, 10, 8, 2]
# }
# Add a column Total (Price × Quantity).
# Find the product with the highest total sales.

data = {
    "Product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "Price": [1000, 800, 400, 300],
    "Quantity": [5, 10, 8, 2]
}

df = pd.DataFrame(data)
df["total"] = df["Price"]*df["Quantity"]
print(df)
dj=np.max(df["total"])
product_with_max_sales = df[df["total"] == dj]["Product"].iloc[0]  # Get the product name

# Print the product with the highest total sales
print(f"\nProduct with the highest total sales: {product_with_max_sales} with total sales of {dj}")

   Product  Price  Quantity  total
0   Laptop   1000         5   5000
1    Phone    800        10   8000
2   Tablet    400         8   3200
3  Monitor    300         2    600

Product with the highest total sales: Phone with total sales of 8000


In [48]:
import pandas as pd
import numpy as np
# Data Statistics:
# Create a DataFrame with 3 columns: Ages, Salaries, and Experience for 6 employees.

# Calculate the mean and median for each column.
# Display rows where Experience is greater than 5 years.

data ={
    "Age":[23,24,45,56,34,45],
    "salaries":[20000,23000,40000,56000,80000,78000],
    "Experience":[2,3,5,6,9,10]
}
df = pd.DataFrame(data)
print(df)
age_mean=np.mean(df["Age"])
sal_mean=np.mean(df["salaries"])
ex_mean=np.mean(df["Experience"])
print("\n",age_mean)
print("\n",sal_mean)
print("\n",ex_mean)

age_mean=np.median(df["Age"])
sal_mean=np.median(df["salaries"])
ex_mean=np.median(df["Experience"])
print("\n",age_mean)
print("\n",sal_mean)
print("\n",ex_mean)

con = df["Experience"]>5
print("\n",df[con])

   Age  salaries  Experience
0   23     20000           2
1   24     23000           3
2   45     40000           5
3   56     56000           6
4   34     80000           9
5   45     78000          10

 37.833333333333336

 49500.0

 5.833333333333333

 39.5

 48000.0

 5.5

    Age  salaries  Experience
3   56     56000           6
4   34     80000           9
5   45     78000          10


In [49]:
import pandas as pd
import numpy as np

data = {
    "Age": [23, 24, 45, 56, 34, 45],
    "salaries": [20000, 23000, 40000, 56000, 80000, 78000],
    "Experience": [2, 3, 5, 6, 9, 10]
}

df = pd.DataFrame(data)
print(df)

# Calculate mean for each column
age_mean = np.mean(df["Age"])
sal_mean = np.mean(df["salaries"])
ex_mean = np.mean(df["Experience"])

# Print the means
print("\nAge Mean:", age_mean)
print("\nSalaries Mean:", sal_mean)
print("\nExperience Mean:", ex_mean)

# Calculate median for each column
age_median = np.median(df["Age"])
sal_median = np.median(df["salaries"])
ex_median = np.median(df["Experience"])

# Print the medians
print("\nAge Median:", age_median)
print("\nSalaries Median:", sal_median)
print("\nExperience Median:", ex_median)

# Display rows where Experience is greater than 5
con = df["Experience"] > 5
print("\nRows with Experience greater than 5 years:")
print(df[con])


   Age  salaries  Experience
0   23     20000           2
1   24     23000           3
2   45     40000           5
3   56     56000           6
4   34     80000           9
5   45     78000          10

Age Mean: 37.833333333333336

Salaries Mean: 49500.0

Experience Mean: 5.833333333333333

Age Median: 39.5

Salaries Median: 48000.0

Experience Median: 5.5

Rows with Experience greater than 5 years:
   Age  salaries  Experience
3   56     56000           6
4   34     80000           9
5   45     78000          10


In [30]:
import pandas as pd
import numpy as np
data = {
    "item":["cookies","bread","rice"],
    "price":[21,45,5],
    "quantity":[5,6,10]
}
df = pd.DataFrame(data)
df
df["total"] = df["price"]*df["quantity"]
print(df)
np.max(df["total"])
np.min(df["total"])


      item  price  quantity  total
0  cookies     21         5    105
1    bread     45         6    270
2     rice      5        10     50


np.int64(50)