In [ ]:
# s =[-10,-18,12,5,7,12,-3]
# d=[8,4,-3,9,2,11]

# s.extend(d)
# s.sort()
# print(s)
# g=len(s)-1
# g=g/2
# g=int(g)
# print("median:",s[g])

# g=len(s)-1
# g=g/4
# g=int(g)
# print("Q1:",s[g])


# g=len(s)-1
# g=g/3
# g=int(g)
# g=g*2
# print("Q3:",s[g])


# whole_num=[1,2,3,4,5,6,7,8,9]
# whole_num2=[7,10,11,12,13,14,15]

# whole_num.extend(whole_num2)
# count=len(whole_num)

# def highest(arr,c):
#     max=arr[0]
#     for i in range(1,c):
#         if arr[i]>max:
#             max=arr[i]                
#     return max
# print(whole_num)

# ans = highest(whole_num,count)
# print("count:",ans)

# evenODD=[1,2,3,4,5,6,7,8,9,10]

# for i in range(1,len(evenODD)):
#     if(evenODD[i]%2):
#         print("odd",evenODD[i])
#     else:
#         print("even",evenODD[i])



True
False


In [6]:
import numpy as np
array = np.array([1,2,3,4,5])
array2= np.array([4,5,6,7,8])
resutl = array + array2
print(resutl)
resutl = array - array2
print(resutl)
resutl = array * array2
print(resutl)
resutl = array / array2
print(resutl)
print('\n')

min = np.min(array)
max = np.max(array)

print('min:',min)
print('max:',max)


[ 5  7  9 11 13]
[-3 -3 -3 -3 -3]
[ 4 10 18 28 40]
[0.25       0.4        0.5        0.57142857 0.625     ]


min: 1
max: 5


In [14]:
import numpy as np
array1 = np.array([[1,2,3,4],[1,24,56,78]])
print(array1.shape)


array2 = np.array([[[1,2,3,4],[1,24,56,78]],[[1,2,3,4],[1,24,56,78]]])
print(array2.shape)
print(array2.ndim)

(2, 4)
(2, 2, 4)
3


In [24]:
import numpy as np

array1 = np.array([1,2,3,4,5])
con = 1<array1
fil = 0
print(array1[con])

[2 3 4 5]


In [30]:
array = np.zeros(5)
print(array)

array = np.ones([5,4])

print(array)

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
array1 = np.full(5,5)

print(array1) 

array2 = np.full((4,5),10) # 4 => row and 5 => column and 10 => write number

print(array2)

[5 5 5 5 5]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
